### ISSUE TITLE
wording not intuitive

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/aoristAAR#2]
Salut :)

I tried to calculate Aorisitic sums using classic BCE from to data. However, BCE values for starting periods are larger than the values for the end of the period. In this case the calculation fails. 

"Failing": 

```r
> from <- c(3100,2800,4100,3100,3100,4100,2800,4100,4100,4100)
> to <- c(2600,2250,3100,2600,2800,3000,2250,3100,3100,3000)
> head(aorist(from = from, to = to))
  date sum
1 2800 NaN
2 2801 NaN
3 2802 NaN
4 2803 NaN
5 2804 NaN
6 2805 NaN
```

"Working":

```r
> from <- c(3100,2800,4100,3100,3100,4100,2800,4100,4100,4100)
> to <- c(2600,2250,3100,2600,2800,3000,2250,3100,3100,3000)
> head(aorist(from = to, to = from))
  date         sum
1 2250 0.003629764
2 2251 0.003629764
3 2252 0.003629764
4 2253 0.003629764
5 2254 0.003629764
6 2255 0.003629764
```

**Comment by OliverNakoinz** [comment]
ohne die aorist Funktion zu kennen würde ich vermuten, dass die Daten ein
negatives Vorzeichen haben müssen, da nur so die BCE Daten in der richtigen
Ordnung sind.
Zum Hintergrund: BCE, BC, AD und dergleichen lagern das Vorzeichen in die
"Einheit" aus. Es sind also letztlich unterschiedliche Skalen. Das
funktioniert aber nicht, wenn man mit den Werten rechnen möchte. Hierzu
benötigen wir eine einheitliche Skala. Es ist ebenso schwierig die
Differenz zwischen 5° Minus in Zelsius zu 3° Plus in Zelsius
(Sprachgebrauch) zu rechnen. Von -5° -(+3)° ergeben aber ohne Probleme 8°.

PD Dr. Oliver Nakoinz
Heisenberg Fellow
Institut für Ur- und Frühgeschichte
Christian-Albrechts-Universität
Johanna-Mestorf-Straße 2-6
D - 24118 Kiel
oliver.nakoinz@ufg.uni-kiel.de
Königsberger Str. 101
D - 24161 Altenholz
+49171/6062913 <0171%2F6062913>
oliver.nakoinz.i@gmail.com <oliver.nakoinz.i@googlemail.com>
https://uni-kiel.academia.edu/OliverNakoinz
https://www.researchgate.net/profile/Oliver_Nakoinz
https://oliver.nakoinz.gitlab.io/OliverNakoinz


2017-10-24 14:49 GMT+02:00 Daniel Knitter <notifications@github.com>:

**Comment by MartinHinz** [comment]
Dear both,

Oliver is absolutely right, data BCE must be given with a negative sign, data CE (AD) are positive. Added that to the documentation in 54fb617

Martin.

@dakni, considering this closed?

**Comment by dakni** [comment]
yep, considered as closed. Thanks for the input and clarification.
